# Site settings
title: TheThunderbox
email: rob@robertdunn.com.au
description: > # this means to ignore newlines until "baseurl:"
  This site is to basically make not of the things that i have
  been doing in regards to WebDev and more, just so i can remember
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thethunderbox.github.io" # the base hostname & protocol for your site
twitter_username: RobHasDunn 
github_username:  thethunderbox

# Build settings
markdown: kramdown
